{
 "title": "Weather App Monitoring",
 "tags": [
  "flask",
  "weather",
  "docker"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"weather-app\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    }
   ]
  }
 ]
}